# Generated by Django 6.0.1 on 2026-01-15 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_alter_loyaltycard_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycard',
            name='cycle_end',
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='cycle_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
