"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

# =====================
# BASE DIR
# =====================

BASE_DIR = Path(__file__).resolve().parent.parent


# =====================
# SECURITY
# =====================

SECRET_KEY = 'django-insecure-6#yr0$vcb8kdvgegh&25li@(4n(tu6%sqj!2giloe03!)g0oap'

DEBUG = True

ALLOWED_HOSTS = []


# =====================
# APPLICATIONS
# =====================

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'drf_spectacular',

    # Local apps
    'loyalty.apps.LoyaltyConfig',
]


# =====================
# MIDDLEWARE
# =====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =====================
# URL CONFIG
# =====================

ROOT_URLCONF = 'config.urls'


# =====================
# TEMPLATES
# =====================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =====================
# WSGI
# =====================

WSGI_APPLICATION = 'config.wsgi.application'


# =====================
# DATABASE
# =====================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =====================
# PASSWORD VALIDATORS
# =====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =====================
# INTERNATIONALIZATION
# =====================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# =====================
# STATIC FILES
# =====================

STATIC_URL = 'static/'


# =====================
# DEFAULT PRIMARY KEY
# =====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =====================
# DJANGO REST FRAMEWORK
# =====================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# =====================
# SWAGGER / OPENAPI
# =====================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Loyalty Card API',
    'DESCRIPTION': 'Loyalty card, bonus, wallet and cycle management system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# =====================
# AUTH REDIRECTS
# =====================

LOGIN_REDIRECT_URL = '/api/loyalty/card/'
LOGOUT_REDIRECT_URL = '/api-auth/login/'
STATIC_ROOT = BASE_DIR / "staticfiles"
